Update factors

diff --git a/factors b/factors
--- a/factors
+++ b/factors
@@ -6,7 +6,7 @@ factorize() {
 
     while ((num > 1)); do
         if ((num % divisor == 0)); then
-            echo "$1=$divisor*$(($num / $divisor))"
+            echo "$num=$divisor*$(($num / $divisor))"
             return
         fi
         ((divisor++))
@@ -16,8 +16,24 @@ factorize() {
 if [ $# -ne 1 ]; then
     echo 'Usage: factors <file>'
     exit 1
-else
-    while read -r line; do
-        factorize "$line"
-    done < "$1"
 fi
+
+if [ ! -f "$1" ]; then
+    echo "File '$1' not found"
+    exit 1
+fi
+
+while IFS= read -r line || [ -n "$line" ]; do
+    re='^[0-9]+$'
+    if ! [[ $line =~ $re ]]; then
+        echo "Invalid input: '$line'"
+        continue
+    fi
+
+    if ((line <= 1)); then
+        echo "Number should be greater than 1: '$line'"
+        continue
+    fi
+
+    factorize "$line"
+done < "$1"
